import Lake
open Lake DSL

/-!
# lakefile.lean — IDE project model only.

Bazel owns the real build and tests in this repository; Lake exists so that
`lake serve` / editors resolve the hand-authored ecosystem imports (`Grpc`,
`Pg`, `Pgx`, `Protovalidate.*`) from the sibling checkouts. Bazel generates
the `AcmeDb`, `AcmeLean`, and `AcmeValid` sources under `bazel-bin`; Lake
recompiles those generated sources into its own coherent IDE build tree.

Refresh generated IDE inputs and use Bazel for validation:

  set -o pipefail
  bazel cquery 'kind(rule, //...)' --output=starlark \
    --starlark:expr='str(target.label) if [key for key in providers(target) if key.endswith("//lean:providers.bzl%LeanGeneratedSourceInfo")] else ""' \
    | sed '/^$/d' | sort -u | xargs -r bazel build --output_groups=lean_srcs
  bazel test //...
-/

package «lean-acme-widgets» where
  leanOptions := #[⟨`experimental.module, true⟩]

require «pg-lean» from "../pg-lean"
require «lean-pgx» from "../lean-pgx"
require «rules-lean-grpc» from "../grpc-lean"
require «protovalidate-lean» from "../protovalidate-lean"
-- Bazel consumes lentil remotely (see MODULE.bazel); the editor project model
-- still resolves `Lentil` / `Config.Config` from the sibling checkout.
require «lentil» from "../lentil"

/- These sources are generated by Bazel. Explicit roots avoid asking Lake for
   nonexistent aggregate `AcmeLean.lean` / `AcmeValid.lean` modules. -/
lean_lib «AcmeLeanGenerated» where
  srcDir := "bazel-bin/proto"
  roots := #[
    `AcmeLean.authz,
    `AcmeLean.service,
    `AcmeLean.user,
    `AcmeLean.widgets,
  ]

lean_lib «AcmeValidGenerated» where
  srcDir := "bazel-bin/proto"
  roots := #[
    `AcmeValid.authz,
    `AcmeValid.service,
    `AcmeValid.user,
    `AcmeValid.widgets,
  ]

lean_lib «AcmeDbGenerated» where
  srcDir := "bazel-bin/db"
  roots := #[`AcmeDb]

lean_lib «Acme» where
  srcDir := "lean"
  roots := #[`Acme]
